### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by mrchristian** [force11/website#164]
the pages are:

Edit in Wordpress - 

[/info/membership-overview-benefits/](https://staging2.simonw59.sg-host.com/info/membership-overview-benefits/)

Edit these two pages in Google Docs. 

https://docs.google.com/document/d/1DqV37NgmwQF_kRcFl0BvJc3LLt--SzlLklk5ekV6RCw/edit?usp=sharing

These are special pages and I need to make further configurations to make them editable. 

We can have a more graphical layout here, if we first work out what the users needs to be informed about I can then have a custom layout made.

[/membership/](https://staging2.simonw59.sg-host.com/membership/)

And a small amount of info here above the form:

[/registration/](https://staging2.simonw59.sg-host.com/registration/)

**Comment by hpiwowar** [comment]
Hi Simon it is actually Todd who will be doing the first draft of this.

**Comment by mrchristian** [comment]
Hi, Yep Todd has drafted the text. But I think you have seen this.

I made a few changes to reflect that 'Group' are not only Working Groups.

And made a few changes to shorten a few phrases.

All content is no on the site and ready to go.

Post launch I will add some graphics and we can review any texts.
