### ISSUE TITLE
Edit page main fundraising page 

### ISSUE THREAD

**Issue by mrchristian** [force11/website#171]
https://staging2.simonw59.sg-host.com/info/fundraising/

**Comment by emmaganley** [comment]
Hi Simon,
I've made suggested edits to the text that you currently have on the fundraising page in this gdoc:
https://docs.google.com/document/d/1hlDV54F_LT6ex_3I-mKGNCWKw_BhbEg5cgMP7qARAvU/edit?usp=sharing
I shared this with you & John - please feedback and/or accept and edit the page as you see fit. 
Thanks,
Emma

**Comment by mrchristian** [comment]
I've moded edits over to site. Any further edits should happen on the live page https://staging2.simonw59.sg-host.com/info/fundraising/
