### ISSUE TITLE
Bottom of home page - funder carousel

### ISSUE THREAD

**Issue by mrchristian** [force11/website#172]
Who should we list here - 

My view is that it should only be current funders, partners, and conference funders.

**Comment by emmaganley** [comment]
Hi - I think probably Sloane, Moore, & CZI given the large grants we had from all three. But I'd like to check this with John/Violeta and maybe Stephanie/Marty to see if this is accurate? 

We also could think about linking to the list of sponsors for the FORCE2021 conference?

Let me know if you need anything more from me.
Thanks,
Emma

**Comment by mrchristian** [comment]
Great, Let me know what people say about who to include. Note there is a FORCE2021 funder carousel at bottom of this page https://staging2.simonw59.sg-host.com/conference/
