### ISSUE TITLE
broken website link (from rebuild)

### ISSUE THREAD

**Issue by danielskatz** [force11/website#199]
We need an alias from `https://force11.org/software-citation-implementation-working-group/` to `https://force11.org/groups/software-citation-implementation-working-group/`

The first link is used in https://force11.org/group/software-citation-working-group and other places around the web, but since the group pages were moved, it doesn't work any more

**Comment by danielskatz** [comment]
I hope this should be very easy to do

**Comment by mrchristian** [comment]
https://force11.org/software-citation-implementation-working-group/

should now be redirected to 

https://force11.org/groups/software-citation-implementation-working-group/

If for some reason it isn't working please let me know.

**Comment by danielskatz** [comment]
Thanks!!
